---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-copier-sa
  namespace: {{ .Values.clusterNamespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-copier-role
rules:
  - apiGroups:
      - "*"
    resources:
      - "secrets"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-copier-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-copier-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-copier-sa
    namespace: {{ .Values.clusterNamespace}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-copier
  namespace: {{ .Values.clusterNamespace}}
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-copier-sa
      containers:
      - image: docker-registry.collibra.com/sf/docker-utility-images:2
        name: copy-secret
        command:
          - sh
          - -c
          - while [ -z "$(kubectl get secret {{ template "user.name" . }} -n {{.Values.clusterNamespace}})" ]; do echo "Wait for {{ template "user.name" . }} secret" && sleep 1; done && kubectl get secret {{ template "user.name" . }} -n {{.Values.clusterNamespace}} --export -o yaml | yq d - metadata.ownerReferences | kubectl apply --namespace={{ .Release.namespace}} -f -"
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          capabilities:
            drop:
              - all
      restartPolicy: Never
  