name: kafka-tenant
version: 0.0.2
id: a2257daa-0e26-4c61-a68d-8a745648Z54
description: "Kafka tenant description"
displayName: "Kafka tenant"

tags: kafka, multi-tenancy
labels:
  experimental: "true"
providerDisplayName: collibra
longDescription: "Kafka tenant long description"
documentationURL: https://github.com/bitnami/bitnami-docker-redis
supportURL: https://bitnami.com/support
imageURL: https://cdn.auth0.com/blog/logos/redis-icon-logo.png
bindable: true